sudo: required
dist: trusty
language: python

python:
    - "3.5"

# command to install dependencies
before_install:
    - git clone https://github.com/amanabt/gmshtranslator.git
    - cd gmshtranslator
    - sudo python setup.py install
    - cd ..
    - sudo apt-get update -qq
    - sudo apt-get install -y build-essential git cmake libfreeimage-dev
    - sudo apt-get install -y cmake-curses-gui
    - sudo apt-get install libopenblas-dev libfftw3-dev liblapacke-dev
    - sudo apt-get install libatlas3gf-base libatlas-dev libfftw3-dev liblapacke-dev
    - sudo apt-get install libglfw3-dev libfontconfig1-dev
    - git clone --recursive https://github.com/arrayfire/arrayfire.git
    - cd arrayfire
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j8
    - sudo make install
    - make test

install:
    - pip install -r requirements.txt

script:
    - python -c "import arrayfire as af"
    - python -c "import dg_maxwell"

