sudo: required
dist: trusty
language: python


python:
    - "3.5"

# command to install dependencies
before_install:
    - pwd
    - ls
    - sudo apt-get purge cmake
    - mkdir ~/temp
    - cd ~/temp
    - wget https://cmake.org/files/v3.9/cmake-3.9.4.tar.gz
    - tar -xzvf cmake-3.9.4.tar.gz
    - cd cmake-3.9.4/
    - ./bootstrap
    - make -j4
    - sudo make install
    - pwd
    - ls

install:
    - pip install -r requirements.txt

script:
    - python -c "import dg_maxwell"
    - pytest
